number:
  key_match: magical_number
  more_than: -10
  even: true

date:
  key_match: date.*
  format: dd/MM/yyyy HH:mm:ss
  day_of_week: monday
  is_before: 27/11/2023
  is_after: 11/11/2023

boolean:
  key_match: bool
  expected: true
